### ISSUE TITLE
ImportError for README instructions

### ISSUE THREAD

**Issue by rjzamora** [jacobtomlinson/jupyterlab-nvdashboard#1]
Beautiful work with this @jacobtomlinson!

I'm running into the following error when I try to follow the README instructions for installation:

```
ImportError: cannot import name 'cpu' from 'jupyterlab_nvdashboard.apps' (/home/nfs/rzamora/miniconda3/envs/cudf_dev_sort/lib/python3.7/site-packages/jupyterlab_nvdashboard/apps/__init__.py)
Traceback (most recent call last):
  File "/home/nfs/rzamora/miniconda3/envs/cudf_dev_sort/lib/python3.7/site-packages/jupyterlab_nvdashboard/server.py", line 7, in <module>
    from jupyterlab_nvdashboard import apps
  File "/home/nfs/rzamora/miniconda3/envs/cudf_dev_sort/lib/python3.7/site-packages/jupyterlab_nvdashboard/apps/__init__.py", line 1, in <module>
    from . import cpu
```

Everything works fine when I just remove the `from . import cpu` line from `jupyterlab_nvdashboard/apps/__init__.py`.

**Comment by jacobtomlinson** [comment]
Yeah my bad, some files got missed from the release. Should be fine in 0.1.3 now.
